### ISSUE TITLE
Upgrade to 1.12.2 or 1.13 ?

### ISSUE THREAD

**Issue by Peda1996** [desht/dhutils#21]
Hello,
Is there any way that you tend to upgrade this utils lib to 1.12.2 or 1.13? I really would like to have chesscraft on my server, but upgrading isn't really possible due to this lib is also out of date, and I can't upgrade this code myself. (not that much knowledge about the used api)

**Comment by desht** [comment]
Sorry, I haven't supported this for years.  I don't even write Bukkit plugins anymore.
